// One-off generator: reads the history-gathering workflow output and writes data/history.ts,
// keeping only editions that self-validated (reconstructed standings == official standings).
//   npx tsx scripts/gen-history.ts <path-to-workflow-output.json>

import { readFileSync, writeFileSync } from "fs";

interface RawGame {
  round: number;
  white: string;
  black: string;
  whiteRating: number;
  blackRating: number;
  classical: "white" | "draw" | "black";
  armageddon: "white" | "black" | "none";
}
interface RawEdition {
  event: string;
  section: "open" | "women";
  year: number;
  games: RawGame[];
  validated: boolean;
  confidence: string;
  notes?: string;
}

const path = process.argv[2];
if (!path) throw new Error("usage: tsx scripts/gen-history.ts <output.json>");

const parsed = JSON.parse(readFileSync(path, "utf8"));
const editions: RawEdition[] = parsed?.result?.editions ?? parsed?.editions ?? [];

const out: Array<Record<string, unknown>> = [];
const included: string[] = [];
const excluded: string[] = [];

for (const ed of editions) {
  const tag = `${ed.year} ${ed.section}`;
  if (!ed.validated) {
    excluded.push(`${tag} (validated=false, confidence=${ed.confidence})`);
    continue;
  }
  included.push(`${tag}: ${ed.games.length} games (confidence ${ed.confidence})`);
  for (const g of ed.games) {
    const rec: Record<string, unknown> = {
      event: `${ed.event} ${ed.year} ${ed.section}`,
      section: ed.section,
      round: g.round,
      white: g.white,
      black: g.black,
      whiteRating: g.whiteRating,
      blackRating: g.blackRating,
      classical: g.classical,
    };
    if (g.classical === "draw" && (g.armageddon === "white" || g.armageddon === "black")) {
      rec.armageddon = g.armageddon;
    }
    out.push(rec);
  }
}

// Aggregate sanity stats.
const nDraw = out.filter((g) => g.classical === "draw").length;
const arm = out.filter((g) => g.armageddon);
const armWhite = arm.filter((g) => g.armageddon === "white").length;

const header = `// Past Norway Chess editions, used as out-of-sample backtest data.
//
// Generated by scripts/gen-history.ts from gathered, self-validated data: each edition's
// per-game results were confirmed by reconstructing the official final standings exactly.
// See CALIBRATION.md for sources and method.
//
// Included editions:
${included.map((s) => `//   - ${s}`).join("\n")}
${excluded.length ? "// Excluded (failed validation):\n" + excluded.map((s) => `//   - ${s}`).join("\n") + "\n" : ""}//
// Totals: ${out.length} classical games, ${nDraw} drawn (${((nDraw / out.length) * 100).toFixed(1)}%),
// ${arm.length} Armageddons, White won ${armWhite} (${((armWhite / arm.length) * 100).toFixed(1)}%).

import type { HistGame } from "@/lib/backtest";

export const HISTORY: HistGame[] = ${JSON.stringify(out, null, 2)};
`;

writeFileSync("data/history.ts", header);

console.log("Included:\n  " + included.join("\n  "));
if (excluded.length) console.log("Excluded:\n  " + excluded.join("\n  "));
console.log(
  `\nWrote data/history.ts: ${out.length} games, draw rate ${((nDraw / out.length) * 100).toFixed(1)}%, ` +
    `Armageddon White rate ${((armWhite / arm.length) * 100).toFixed(1)}% (n=${arm.length}).`,
);
